on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_gcc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: df -h
      # cleanup some steps
      - run: dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n
      # ~7GB
      - run: sudo apt purge -y azure-cli google-cloud-cli microsoft-edge-stable dotnet-* temurin-* google-chrome-stable llvm-* firefox powershell
      - run: df -h
      #~10 GB
      - run: sudo du -hc /opt
      #~5 GB
      - run: sudo du -hc /var
      - run: sudo rm -rf /opt/*
      - run: sudo rm -rf /var/*
      - run: docker run -it hello-world
      - run: podman run -it hello-world
      - run: df -h
      - run: sudo du -hc /
