on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_gcc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: df -h
      - run: dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n
      - run: sudo apt purge -y azure-cli google-cloud-cli microsoft-edge-stable dotnet-* temurin-* google-chrome-stable llvm-* firefox powershell
      - run: df -h
      - run: du -hc /opt
      - run: du -hc /var
      - run: du -h /
