on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_gcc:
    runs-on: ubuntu-latest
    strategy:
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: df -h
