on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_gcc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: df -h .
      - run: sudo ls
      - uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 0
          remove-dotnet: 'true'
      - run: df -h .
